### ISSUE TITLE
Allow multiple queries for the same panel.

### ISSUE THREAD

**Issue by squaresurf** [hakobera/influga#29]
Would you be open to allowing multiple queries to be written for a single panel so you can see the comparison of multiple time series?

**Comment by Oliv4945** [comment]
Hi, I am also thinking that it might be good

**Comment by hakobera** [comment]
@squaresurf @Oliv4945 This project no longer maintained. If you use InfluxDB 0.9+, you can do it using [re:dash](http://redash.io/)
