### ISSUE TITLE
Is Influga is still a live project?

### ISSUE THREAD

**Issue by hugogoncalves** [hakobera/influga#31]
Hi! I´m evaluating influga. This project is still alive?

**Comment by wolkykim** [comment]
also does it support influx 0.9?

**Comment by seregasheypak** [comment]
Elvis has left the building?

**Comment by grahamlyons** [comment]
@hakobera, is this project no longer supported?

**Comment by hakobera** [comment]
@wolkykim @seregasheypak @grahamlyons This project is no longer maintained. So you should use alternatives.

See #32
